apiVersion: v1
kind: Service
metadata:
  name: student-dropout-predictor
  labels:
    app: student-dropout-predictor
spec:
  selector:
    app: student-dropout-predictor
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer